server:
  port: 30000
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: xiaomao-third-party
  datasource:
    url: jdbc:mysql://localhost:3306
    driver-class-name: com.mysql.jdbc.Driver
