spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    gateway:
      routes:
#        - id: query_qq
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq
#
#        - id: query_baidu
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu

        - id: product
          uri: lb://xiaomao-product
          predicates:
            - Path=/api/xiaomaoproduct/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: coupon
          uri: lb://xiaomao-coupon
          predicates:
            - Path=/api/xiaomaocoupon/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: member
          uri: lb://xiaomao-member
          predicates:
            - Path=/api/xiaomaomember/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: ware
          uri: lb://xiaomao-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /xiaomao$\{segment}

        - id: third-party
          uri: lb://xiaomao-third-party
          predicates:
            - Path=/api/third/party/**
          filters:
            - RewritePath=/api/third/party/?(?<segment>.*), /$\{segment}

        - id: admin
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}
    nacos:
      server-addr: 127.0.0.1:8848
server:
  port: 88
